f = open('android/build.gradle', 'w') 
f.write('buildscript {\n') 
f.write('    ext.kotlin_version = "1.9.0"\n') 
f.write('    repositories {\n        google()\n        mavenCentral()\n    }\n') 
f.write('    dependencies {\n') 
f.write('        classpath "com.android.tools.build:gradle:8.7.0"\n') 
f.write('        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"\n') 
f.write('    }\n}\n') 
f.write('allprojects {\n    repositories {\n        google()\n        mavenCentral()\n    }\n}\n') 
f.write('rootProject.buildDir = "../build"\n') 
f.write('subprojects {\n    project.buildDir = "${rootProject.buildDir}/${project.name}"\n}\n') 
f.write('subprojects {\n    project.evaluationDependsOn(":app")\n}\n') 
f.write('task clean(type: Delete) {\n    delete rootProject.buildDir\n}\n') 
f.close() 
